### ISSUE TITLE
[FEATURE REQUEST] Support for Album based DPLs in the new Material Home Hero section

### ISSUE THREAD

**Issue by mikeysas** [AF-1/lms-dynamicplaylists#19]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your request mentioned in the FAQ?

- [x] I have searched the FAQ

### Is your feature request related to a problem?

Nope

### Describe the solution / feature you'd like

@AF-1  - adding this as a feature request as I know you don't get notified by the Forum.  Understand if you prefer to move the discussion there as this is more of a heads up based on ongoing development.

Have you seen the latest update to Material Skin with the new Home Hero section (Horizontal Scrolling lists for things like New Music, Random Albums, Playlists, Radio Favorites etc.)?  Michael is working with Craig on adding support for Plugins to add new lists as options for the Home Hero section.  See the ongoing discussion https://forums.lyrion.org/forum/developer-forums/developers/1794833-extending-the-material-home-hero-section and the Draft PR https://github.com/CDrummond/lms-material/pull/1124.

I really see value in having the Random Albums list on the Home Screen as a cool music discovery where I can be inspired by something I have not heard in while randomly.  This got me thinking that if you were interested also, it would be even better to have the option to define Home Hero list of Random Albums based on the criteria that drives an Album based DPL, but instead have it populate a user defined # of Albums into the Home Hero item.  For me I would use that new DPLC Template you created for Random Albums from a Virtual Library as I like how that allows me a rich set of criteria but keeps whole Albums. However, I think any Album based DPL could be used as an option for a Home Hero list.

I don't know if this is beyond the scope of what you consider a feature for DPL / DPLC and maybe it would be cleaner to be built as a separate Plugin that shares your same code base and concepts, but I love the idea of being able to use the power you have enable with DPL / DPLC + VLC to define more refined versions of the Random Album option delivered with Material 6.0.1.  For example I would define one that uses ratings 3+ and not played in over a year.

### LMS version

9.0.4

### Plugin version

4.5.7

### Anything else?

I am not sure if you are much Material user, but if you have not checked out the new Home Screen in the latest Material, you should and see if that is of interest to you.  I understand if this is outside your scope / interest and of course this is all dependent on Michael and Craig completing the plugin extendability for this new Home Hero section.  Thanks for considering.

**Comment by AF-1** [comment]
I must admit, I'm not a Material user. I took a look at Material 6.0.3. BTW why is the new feature called _Hero_?

So you're suggesting a horizontally scrollable line for albums and maybe artists based on custom sqlite queries?
We'll have to wait and see how exactly the 3rd party plugin integration is implemented eventually and what parameters Material expects 3rd party plugin to provide. Will it expect plugins to provide only sqlite statements and would then go on to fetch the objects itself... or will Material expect a list of album/artist ids... 
All I can say for now is that I feel that creating a completely new plugin just for populating one or two Material Hero lines seems a bit excessive. But if the plugin integration works for me, I would probably give this a try.

**Comment by mikeysas** [comment]
> BTW why is the new feature called Hero?

I have no idea???  I did not even know it was called that until, I saw the reference in Michael’s forum post that I linked above.  That thread and the PR I linked may provide you more insight on the current plans for extensibility via Plugins.

I believe that the horizontal scrolling items that Craig implemented are all standard LMS queries that he calls vis JSON (but I am not the technical guy for sure).  For example I am pretty sure Michael implemented new calls for him in 9.1 to support the Recently Played and Most Played as those are only available in LMS 9.1.

This is Michael’s plan initially using Spotty as an example from the thread I linked, but obviously need to watch how and if it actually gets implemented.

> - Material plugin provides a "registerHomeHeroSection(identifier, labelToken, handler)" hook for plugins to register their handler(s). "identifier" would be the internal ID used in your query (eg. "spotty-recommendations"), "labelToken" a string token to localise the title shown (or a plain string if that simplified things? Up to the plugin to localise?), the "handler" a code ref to be called by Material.
> - Material frontend lists the above options together with its own to be selected by the user
> - Material frontend queries the plugin with the new ids as additional parameters: "material-skin home-extra new:1 radios:1 spotty-recommendations:1"> 
> - Material plugin looks up handler with the key
> - Material plugin calls the handler with the client object and a callback to be called with the list of menu items
> - Material's callback receives a list of SlimBrowse menu items and adds them to the response

EDIT:
FYI - I fixed the links in my original post which were not working when you clicked.

**Comment by mikeysas** [comment]
@AF-1 Material 6.1 was released with support for plugins adding Horizontal Scroll Items.  You can see examples of how Michale implemented it in the Spotty and Bandcamp plugins if you are still interested in giving this a try.

**Comment by AF-1** [comment]
I will have a  look but probably won't get anything done this month. In the meantime, you could do me a favor and test the latest repo version of DPL 4.5.**8**. My LMS doesn't show me dynamic playlists saved as favs in the DSTM mixer option menu. 
So I integrated this directly into DPL. You can add eligible dynamic playlists (eligible =  they do not request parameters from the user at run-time) as DSTM mixer options (by clicking on the infinity icon next to the playlist in the DPL plugin settings > Enabled playlists). I was mainly thinking of dynamic playlists created with DPLC.
DSTM will then add a url to the end of the current client playlist (basically as if you added it manually) to start the dynamic playlist once the last track has finished. 
One quirk: since DSTM adds a url and not tracks I had the choice: 
either DSTM adds a placeholder with an icon and no text (default skin) and even uglier in Material (text = 3 times "unknown")
OR add the icon with the correct dynamic playlist name (in both skins) BUT DSTM will add a randomplay track mix placeholder after the DPL placeholder (because it expects tracks, doesn't get any, therefore adds randomplay fallback mix). 
It is just a UI matter because the randomplay placeholder is never executed. It is cleared with the rest of the client playlist once the dynamic playlist starts. I did some (successful) tests but didn't have the time for more.

**Comment by mikeysas** [comment]
>My LMS doesn't show me dynamic playlists saved as favs in the DSTM mixer option menu.

There is an option to enable that on Settings > Advanced > Favorites. 

Running out now, but will try to test it later this evening or tomorrow.

**Comment by mikeysas** [comment]
I tested both using a Favorite of a DPL for DSTM and your new DSTM option and they both are working well and wait for the end of the last track to complete before starting.

I also tested what would happen if I took one of my DPLs that is a Favorite and also enabled it for DSTM using your new option.  Don't know if you accounted for that or if DSTM just handles it, but it only showed up once on the DSTM selector which is good.

Seems good to go.  The UI quirk does not bother me either way.  In my tests it was doing the Unknown placeholder which is what it has always done for Favorites also.  If you prefer the getting the correct icon and name, I don't think anyone should mind that a random play placeholder is stuck after it since it will never get there.

FYI - I ran all my test in Material on v9.0.4

**Comment by AF-1** [comment]
Thank you for testing.

> I also tested what would happen if I took one of my DPLs that is a Favorite and also enabled it for DSTM using your new option. Don't know if you accounted for that or if DSTM just handles it, but it only showed up once on the DSTM selector which is good.

How do you get faved dynamic playlists to show up in the DSTM mixer options menu? I'm on 9.0.4 and the only DSTM options that show up are those registered by plugins like Ratings Light, Random Play and now DPL. But I've never seen a favorite there. Maybe some setting I changed and forgot about?

**Comment by mikeysas** [comment]
You probably missed my reply above on the setting to include favorites on DSTM

>There is an option to enable that on Settings > Advanced > Favorites.

**Comment by AF-1** [comment]
I took a look at Material, Spotty, etc. and the Home Extras Menus. 
Unfortunately, it does't seem to be a good fit. Here's why IMHO:
HomeExtras are statically registered: Material Skin requires every HomeExtra to have a fixed identifier (tag) when the plugin starts. Once registered, the system caches them for the whole session. There’s no way to register/add, unregister or rename HomeExtras on the fly. Dynamic content is allowed, but not dynamic slots: You can fill a HomeExtra with dynamic content (e.g., tracks, albums, playlists). You cannot dynamically create a new HomeExtra for each playlist, because Material Skin won’t recognize it. Even tricks like pre-creating “slots” often fail, because closures and caching can make the UI point to the wrong slot, or show empty placeholders. Every change to a Home Extra would require a server restart. DPL(C) would let users create any number of playlists. But static HomeExtra slots cannot reliably map to an unknown number of playlists. I've really tried to make this work but there is no satisfying solution.
I hope this does not sound too confused. In the end, it does not seem a good fit for DPL(C).
A better reliable solution would be a dedicated plugin that provides predefined HE menus. Sorry.

P.S.
>  For example I would define one that uses ratings 3+ and not played in over a year.

Maybe I'll something like that to Ratings Light next year.

**Comment by mikeysas** [comment]
Thanks for taking the time to look into this and thinking about it.  I think I get the challenges you explained with the way Material handles this.

Question:
What if you look at this simpler and just implement a single predefined home menu item called Dynamic Discovery which is defaulted to one of the predefined DPLs but allows the user to select from any valid DPL(C) to use as the criteria for populating Dynamic DIscovery?  Would that be doable? 

I suggest this still for DPL over Ratings Light because the user can decide if it is a track, album or artists list based on the DPL.  I am primarily interested in a home item that is like Random Albums but with the ability to control the criteria better.  I would never use a track based one, but would consider Artist based also as interesting.  If you implemented something in Ratings Light, would that have to be tracked based or could it be Top Rated Albums?  Of course then that opens the question of is that average rating or at least one track etc.  Sorry.  I appreciate you thinking about it.  

Honestly, if you prefer the flexible approach in DPL, I would also be ok with the idea that defining new DPL based Home Menu items requires a server restart.  It is not something I would do very often anyways.

**Comment by michaelherger** [comment]
FWIW: I don't understand all the implications of this plugin. I have a plugin with changing content, too: 1001 Albums. But that only changes once a day. So this might be somewhat different. A page reload usually is all I need to do to get the latest album(s). 

Are you saying the "heroes" aren't working for you because by the time a user selected an item from a scrollable area the items in that view might already have changed in the background?

**Comment by mikeysas** [comment]
@michaelherger, I think the concern is not the dynamic nature of the content within a horizontal scroll item, but instead the dynamic nature of defining a new horizontal scroll item.

Since you are not that familiar with this plugin, instead consider the request from the forum to which my response pointed here as I see the issue as similar.  The forum user was asking if a horizontal scroll item could be defined to display a Library View.  Although not explicitly stated, for the illustration, let’s assume the request was for a random ordered list of albums from the Library View.  But since a user can keep defining new Library Views at any time, what if the user wants to add a 2nd new Library Views as an additional Horizontal Scroll item.

@AF-1  describes that Material requires the plugin to register Horizontal Scroll items at startup of LMS and that there is some caching involved.  So although it sounds more straight forward to create a plugin that supports the selection of a single Library View to display a random list of albums (which could be changed to a different library view at anytime), I interpreted from @AF-1 ’s comment, that it would not be possible to allow the user to select a 2nd Library View to add to the Horizontal Scroll Items without forcing a restart of the server.

Since users can define a new custom DPL at any time similar to Library Views, I see the two as having the same structural concern.  Maybe there is a simple solution to support the dynamic creation of a new Horizontal Scroll item or maybe not.  As a user, I don’t feel like I would create a new Horizontal Scroll item very often and if that required me to restart the server as that is the only solution, I would be fine with that.  I think users would rather have the option to define more customized horizontal scroll items even it it requires a server restart to add a new one.  

It sounds like you could change the definition of the query behind an existing scroll item without having to restart, but no idea if you can change items name easily.

Does that help explain the concern?  Of course this was just my interpretation of it.

**Comment by michaelherger** [comment]
Thanks for the additional information, @mikeysas. But I think _adding_ an item shouldn't need a restart. A page refresh should do. But yes, that would be needed (like my 1001 Albums example). What currently certainly is not supported is removing an item. But that's just because it hasn't been implemented yet. I believe it should be easy to do in Material (I could take care of that). 

@CDrummond - would you be interested in a mechanism to let a plugin tell Material that it should refresh the scrollable areas?

**Comment by CDrummond** [comment]
@michaelherger Sounds fine with me :)

**Comment by AF-1** [comment]
I am currently looking into this, even it is at turtle speed. 
When @mikeysas suggested this, before it was implemented, I thought I need something similiar to how DSTM handles things: functions to register and unregister Home Extras any time.
Looking at how Spotty and Bandcamp create HE lists, it seems to me that the title of the HE lists have to be set quite early, not sure how to change them later on. I would prefer to have the user-defined title but I guess "Dynamic Album Discovery 1" and 2 should also do. I think I don't actually need a function to delete or remove lists anymore. If the users changes or disables a slot, Material will probably show nothing.
I will create 2 Dynamic Album Discovery HE items for now and let the user select an SQLite definition of his choice in the DPL plugin settings.
@CDrummond / @michaelherger 
1. is the number of items displayed in these horizontal lists automaticlly limited by Material (based on predfined settings or screen width), or do I have to pass a limit somewhere? (in handlefeed?)
2. And what input does Material actually expect from a plugin that delivers album or artist ids? Just an array of hashes with type => album and then id => {somealbumid)?

**Comment by mikeysas** [comment]
> Thanks for the additional information, [@mikeysas](https://github.com/mikeysas). But I think _adding_ an item shouldn't need a restart. A page refresh should do. But yes, that would be needed (like my 1001 Albums example). What currently certainly is not supported is removing an item. But that's just because it hasn't been implemented yet. I believe it should be easy to do in Material (I could take care of that).
> 
> [@CDrummond](https://github.com/CDrummond) - would you be interested in a mechanism to let a plugin tell Material that it should refresh the scrollable areas?

Rereading this, I am wondering if my choice of the word "item" was poor and misleading.  The item I was referring to is a new Horizontal Scroll List and not an individual element on the list in case that was not clear.

For example let's say I create a Library View (or DPL) called "Top rated Jazz from the 1960's" and then want to add that so it appears as a random ordered list of Albums on my Home Screen.  Could a plugin push a new Horizontal Scroll List selection like my example and make it available in Material for the user to select from the Interface Settings?

I think this is why @AF-1 is looking at creating two predefined Dynamic Album DIscovery lists where the user can decide which DPL query to associate with each one.  I know that would work very well for me although the ability for the user to change the name on them would be a bonus.

**Comment by michaelherger** [comment]
> 1. is the number of items displayed in these horizontal lists automaticlly limited by Material (based on predfined settings or screen width), or do I have to pass a limit somewhere? (in handlefeed?)

Material would request a number.

> 2. And what input does Material actually expect from a plugin that delivers album or artist ids? Just an array of hashes with type => album and then id => {somealbumid)?

I simply return the full menus as defined in `handleFeed` etc. Look eg. at https://github.com/michaelherger/1001Albums/blob/master/HomeExtra.pm. There's really no new magic to implement. In your case you might want to define what browse mode you want to return. But what you return is the same thing as you'd return when requesting the normal menus.

**Comment by michaelherger** [comment]
Wow... installed this plugin - and I am overwhelmed by its options. I don't even understand what of this you'd want to have in a scrollable area. @mikeysas would you expect to have the result of some of all those mixes? Or a selection of mixes? 

If the former (which I understand from the original description), then I believe it would be as simple as registering with Material, giving the name of that mix, and a hook to get the results of the mix. That hook would probably do the same as the "Create DSTM seed list..."?

> For example let's say I create a Library View (or DPL) called "Top rated Jazz from the 1960's" and then want to add that so it appears as a random ordered list of Albums on my Home Screen. Could a plugin push a new Horizontal Scroll List selection like my example and make it available in Material for the user to select from the Interface Settings?

Of course a plugin can do that. Many of mine do.

> I think this is why [@AF-1](https://github.com/AF-1) is looking at creating two predefined Dynamic Album DIscovery lists where the user can decide which DPL query to associate with each one. I know that would work very well for me although the ability for the user to change the name on them would be a bonus.

~~Why "two predefined Dynamic Album Discovery lists"? Couldn't any of the lists be exposed? What would each of the two do?~~ (sorry, I somehow skipped reading the first part of @AF-1 's response...)

**Comment by AF-1** [comment]
> But I think _adding_ an item shouldn't need a restart. A page refresh should do.

> For example let's say I create a Library View (or DPL) called "Top rated Jazz from the 1960's" and then want to add that so it appears as a random ordered list of Albums on my Home Screen. Could a plugin push a new Horizontal Scroll List selection like my example and make it available in Material for the user to select from the Interface Settings?

Looking at Spotty's HomeExtras.pm: there is a fixed list of Home Extras lists / slots - with fixed names (from the strings.txt). And they are initialized via initPlugin calls very early on after a server restart. 
So can I really add another _totally new_ Home Extras list that hasn't been initialized there yet at **any** time? If so, how would that work?

@michaelherger Never mind all the predefined dynamic / smart playlists that come with DPL. The general idea behind it is: the user defines a custom sqlite statement (e.g. using the DPLC plugin's UI) and DPL will retrieve **track** ids for this mix and add them to a client playlist in batches. 
For Home Extras lists I'd need album or artists ids. No problem. I don't recall having to deal with LMS browse menus in depth before. Maybe you can help me out here. Let's say I have retrieved some album ids in an array. How do I pass them back so Material displays the list/menu? 

So the HomeExtras could look like this:

````
package Plugins::DynamicPlaylists4::HomeExtras;
use strict;
use warnings;

Plugins::DynamicPlaylists4::HomeExtraDynamicAlbumDiscovery01->initPlugin();
# Plugins::DynamicPlaylists4::HomeExtraDynamicAlbumDiscovery02->initPlugin();
# Plugins::DynamicPlaylists4::HomeExtraDynamicAristDiscovery01->initPlugin();

1;

package Plugins::DynamicPlaylists4::HomeExtraBase;
use strict;
use warnings;
use utf8;
use base qw(Plugins::MaterialSkin::HomeExtraBase);

use Slim::Utils::Prefs;
use Slim::Utils::Log;
use Plugins::DynamicPlaylists4::Plugin;

my $log = logger('plugin.dynamicplaylists4');
my $prefs = preferences('plugin.dynamicplaylists4');

sub initPlugin {
	my ($class, %args) = @_;

 	my $tag = $args{tag};

	$class->SUPER::initPlugin(
		feed => sub { handleFeed($tag, @_) },
		tag  => "DynamicPlaylists${tag}",
		extra => {
			title => $args{title},
			subtitle => $args{subtitle},
			icon  => $args{icon} || Plugins::DynamicPlaylists4::Plugin->_pluginDataFor('icon'),
			needsPlayer => 1,
		}
	);
}

sub handleFeed {
 	my ($tag, $client, $cb, $args) = @_;
 
 	$args->{params}->{menu} = "home_heroes_${tag}";
  	$args->{params}->{tag} = $tag;

	Plugins::DynamicPlaylists4::Plugin::handleFeed($client, $cb, $args);
}

package Plugins::DynamicPlaylists4::HomeExtraDynamicAlbumDiscovery01;
use base qw(Plugins::DynamicPlaylists4::HomeExtraBase);
sub initPlugin {
	my ($class, %args) = @_;

	$class->SUPER::initPlugin(
		title => 'SETTINGS_PLUGIN_DYNAMICPLAYLISTS4_HOMEEXTRASMENUS_ALBUMS01',
		tag => 'dynamicalbumdiscovery01'
	);
}
1;
````

And this part in Plugin.pm:


````
sub handleFeed {
...
# here: everything to get the album ids
...
unless (@albumIDs) {
        $cb->([]);
        return;
    }

# and now what?
    require Slim::Menu::BrowseLibrary;

    Slim::Menu::BrowseLibrary::_albums(
        $client,
        $cb,
        {
        	mode => 'albums',
        	???????
        	???????
        }
    );
    return;
}
```` 

Something with feed and url? If possible, I would like to retrieve the ids in DPL and not pass the sqlite statement to LMS to let LMS retrieve the items. Because if the sqlstatement is faulty, I suppose LMS / Material would fall back to showing all albums (in this example). I hope this makes sense.

**Comment by mikeysas** [comment]
> Wow... installed this plugin - and I am overwhelmed by its options. I don't even understand what of this you'd want to have in a scrollable area. [@mikeysas](https://github.com/mikeysas) would you expect to have the result of some of all those mixes? Or a selection of mixes?

@AF-1 got it right.  I don't really use the predefined DPLs that come with the plugin.  If you install the Dynamic Playlist Creator also, then you can be a power user too 🤣

It has a set of templates that make it easy for a user like me to build custom Dynamic Playlists. Since I prefer to listen to whole albums most of my Dynamic Playlist were created using my favorite template, Random Albums from a Virtual Library (thanks again @AF-1 for creating that one!).  It ensures that only whole albums are added to the playlist even if the virtual library definition contains only some of the tracks from the album.  So in my example above I can easily create a DPL that will randomly add Jazz albums from the 1960's that contain at least one top rated track.  That is not exactly what I am looking for, but it is a good easy to follow example of the possibilities that you can do here.  I am looking to add a similar style query as a Home Extra list that is essentially will be a better albums discovery list than the default random albums because I can add interesting criteria that will limit and/or bias what will be included.

Currently I have a default Whole Album Dynamic Playlist that drives much of my listening.  I have it configured to add multiple albums and then I remove any that I am not in the mood to listen to at that time.  I can always play something specific and then DSTM will kick my DPL back in.  My hope is to have my DPL definition populate a list of albums on the home screen that I could manually select from (as a short list) based on my current preference if I wish and then the DPL can still kick in additions when it hits the end if I have not added another.  That is my objective, but based on some of the discussion in the forum, I think there is good interest for Album Discover with some criteria control like exclude certain genres and low rated albums.

**Comment by michaelherger** [comment]
> [@michaelherger](https://github.com/michaelherger) Never mind all the predefined dynamic / smart playlists that come with DPL. The general idea behind it is: the user defines a custom sqlite statement (e.g. using the DPLC plugin's UI) and DPL will retrieve **track** ids for this mix and add them to a client playlist in batches. For Home Extras lists I'd need album or artists ids. No problem. I don't recall having to deal with LMS browse menus in depth before. Maybe you can help me out here. Let's say I have retrieved some album ids in an array. How do I pass them back so Material displays the list/menu?

TBH: that's nothing I could answer off the top of my head. I'd have to tinker some, too. But I think your approach is pretty sane. Using `BrowseLibrary` certainly would save you a ton of work dealing with the details of browsing local content. (My implementations don't deal with that, so that's simpler).

> And this part in Plugin.pm:
> 
> ```
> sub handleFeed {
> ...
> # here: everything to get the album ids
> ...
> unless (@albumIDs) {
>         $cb->([]);
>         return;
>     }
> 
> # and now what?
>     require Slim::Menu::BrowseLibrary;
> 
>     Slim::Menu::BrowseLibrary::_albums(
>         $client,
>         $cb,
>         {
>         	mode => 'albums',
>         	???????
>         	???????
>         }
>     );
>     return;
> }
> ```
> 
> Something with feed and url? If possible, I would like to retrieve the ids in DPL and not pass the sqlite statement to LMS to let LMS retrieve the items. Because if the sqlstatement is faulty, I suppose LMS / Material would fall back to showing all albums (in this example). I hope this makes sense.

Yeah, what to pass to those methods... two approaches crossed my mind:

1. You create libraries on the fly. Your query would define a library with only the tracks of your selection, and you pass the `library_id` to `_albums` etc. Libraries are always tracks. So you'd have to fetch these for your albums. But LMS/SQLite is pretty effective doing such manipulations.
2. You try to find a `searchTags` parameter combination which would fit your needs. I believe the `albums` query would accept an `album_id` which _can_ be a comma concatenated list of album IDs. So you'd pass something like `album_id:1,22,333`. If that works, it might be more efficient and easier to implement than the library approach.

As I said, that's just ideas. I'm pretty sure you'll have to do some tests (and failures). But hopefully it's a starting point.

**Comment by michaelherger** [comment]
Argh... I believe the concatenated ID trick doesn't work for contributors (`artists` query)...

**Comment by AF-1** [comment]
@michaelherger I'm not even sure that concatenated _album_ IDs work with searchTags. At least I couldn't make that work. 
Same for `library_id`. I used the real id of an existing virtual library (e.g. fd7d0465) to limit the albums displayed in the Material home extra 'menu' - and it did not limit anything. Tried to pass it directly in $args and even in $pt. No limiting effect. It's as always: ALL albums are listed.That was a bit surprising.
The thing is - I have everything else in place in the DPL and DPLC plugins. But just no way to display the correct results in Material.
Bit frustrating. I've searched the LMS core code for inspiration but TBH I'm all out of ideas.

**Comment by michaelherger** [comment]
Would you have a branch I could play with? Where you have everything up to the BrowseLibrary calls which don't work?

**Comment by AF-1** [comment]
Just pushed the `homeextras` branch. 
I've included a Home Extras example **sql** file (_material_he_test_rnd_albums_multigenres.sql_), so you don't have to install the Dynamic Playlist _Creator_ plugin (which does not have such a branch, it's not relevant to the problem anyway). 

Just move the sql file to the folder called `DPL-custom-lists`. The parent folder is probably the one with the persist.db file unless you changed that in the plugin settings. 

If you enter the DPL menu in LMS home, DPL rescans the folder and picks up the example file/definition. Also useful if you adapt the sql part in the sql file to your needs. 

In the DPL plugin settings you can link it to Dynamic Album Discovery 1, the Material Home Extras menu item.

**Comment by michaelherger** [comment]
You were close there 😉. The issue why the filter didn't work was that you missed one parameter: `_albums` would have expected another parameter before your arguments. I'm using an empty object `{}` in below code.

That said: more work is/was needed to make it work as expected. LMS would drill down the navigation tree when trying to play an item. With items in random order this is problematic, as when you get back to actually play something, the order will be different, resulting in the wrong item being played.

The other challenge is that the multiple IDs wouldn't work artists, IIRC. And there would be a non-working "All Tracks" item. Therefore my suggested approach is slightly different. I'd recommend you get each item individually, ID by ID. This certainly is more "costly", but Home Extras usually only display 10 items. So this shouldn't be too much of a hassle.

I'm using `Async::Util::amap`, which would take a list as input, and call a sub with each element of the list. The final callback would pick up the collected results and do whatever is needed. The input therefore is the ID list as before. Then I call `_albums` for each of them, resulting the items in the final callback. Or `_artists`. This deals with the latter's inability to consume multiple IDs. Or return results in random order.

To deal with the randomisation I'm caching the list of IDs: if we're asked for a list of items, crate a new list. If we're asked to play one specific item, get the list from the cache, extract the ID, and only return that one item.

```diff
diff --git a/DynamicPlaylists4/Plugin.pm b/DynamicPlaylists4/Plugin.pm
index 3af4a24..66611c1 100644
--- a/DynamicPlaylists4/Plugin.pm
+++ b/DynamicPlaylists4/Plugin.pm
@@ -7353,6 +7353,12 @@ sub getHomeExtraMenuItems {
 			return;
 		}
 
+		my @items;
+		my $cacheKey = "dpl_homeExtra_$tag";
+		if ($args->{params} && $args->{quantity} == 1 && defined $args->{params}->{item_id} && (my $cached = $cache->get($cacheKey))) {
+			@items = @{$cached}
+		}
+		else {
 			my $playlistName = $playlist->{name};
 	# 		$log->info('playlistName = '.Data::Dump::dump($playlistName));
 			my $localDynamicPlaylistSQLstatement = $localDynamicPlaylist->{'sql'};
@@ -7383,7 +7389,6 @@ sub getHomeExtraMenuItems {
 			$log->info('sqlstatement = '.$sqlstatement);
 
 			my $dbh = Slim::Schema->dbh;
-		my @items;
 
 			for my $sql (split /[\n\r]+/, $sqlstatement) {
 				next unless $sql =~ /\S/;
@@ -7406,19 +7411,34 @@ sub getHomeExtraMenuItems {
 				return;
 			}
 
+			$cache->set($cacheKey, \@items);
+		}
+
 		require Slim::Menu::BrowseLibrary;
+
+		Async::Util::amap(
+			inputs => \@items,
+			action => sub {
+				my ($albumId, $acb) = @_;
 				Slim::Menu::BrowseLibrary::_albums(
 					$client,
-			$cb,
+					$acb,
+					{},
 					{
-# 				library_id => 'fd7d0465'
-				searchTags => [
-					'album_id:'.join ",", @items
-				]
+						searchTags => [ "album_id:$albumId" ]
 					}
 				);
+			},
+			cb => sub {
+				my ($albumMenuItems, $error) = @_;
 
+				my @items = map {
+					@{ $_->{items} }
+				} @$albumMenuItems;
 
+				$cb->({ items => \@items });
+			}
+		);
 	}
 	return;
 }
```

This diff ignores whitespace changes to only show the actual changes. You might want to fix indentation.

Trust me when I'm saying I would not be able to come up with something like that off the top of my head. I never remember details of eg. `BrowseLibrary`. It always requires me to add a log statement or two in there to figure out what's going on. I'd strongly recommend developers to run their dev LMS off a git clone, so they can add those log statements to help them understand the flow. It's when I dumped `_albums`' parameters when I noticed you were missing one of them.

**Comment by AF-1** [comment]
Thank you very much, @michaelherger
Here's how it works right now: users can create menu "definitions" (custom sqlite statements) for Material Home Extras menus (albums or artists) with the **Dynamic Playlist _Creator_** plugin which are then picked up and processed by the **Dynamic Playlists** plugin. 
DPL has three slots: 2 called Dynamic _Album_ Discovery and one Dynamic _Artist_ Discovery. Users can link menu definitions created with DPLC to one of the slots in the DPL settings. If the user selects a different menu definition later, Material will use the new custom sqlite statement after a page refresh. If no valid menu definition is found for one of the slots, Material does not display anything, even if you added the 3 slots permanently to Material's Home page.

The _title_ of Home Extras menus (horizontal scrollable list) is set pretty early on in HomeExtras.pm (e.g. 'Dynamic Album Discovery') and remains fixed. For other plugins that makes sense. 
In my case, Ideally, DPL should use the name of the actual menu definition that the user linked to this Home Extras menu (e.g. 'Rated Jazz Tracks') and use that title. And update it if a user select a different menu definition. 
Please correct me if I'm wrong but I'm not sure this is possible at the moment, or is it? Or is it related to the Material 6.1.3 changelog item (for which I didn't find a related commit): 
> Allow list of 3rd party scrolled lists to be updated.

BTW if you pass a `subtitle` to Material for a Home Extras menu, where and under which conditions would this subtitle be displayed?

@mikeysas Would you be interested in testing the 2 DPLC Material Home Extras Menus **templates** (albums, artists) by creating lots of Home Extras menus with different options? I did a very rudimentary test (e.g. included genres, multi-discs) but I simply don't have the time at the moment to test all or even most of the options.
If so, there is a `homeextras` branch for DPL and DPLC you can use. Thanks.

**Comment by michaelherger** [comment]
Material change to trigger re-reading Home Extras: https://github.com/CDrummond/lms-material/commit/04eca1f2e7ca68cceb1a8e730f91e9dadbe9f143#diff-87003bfc44c0fc31395ef1ae8af03d325d08dfd8ccd4bfbfd888735e388c0f1dR570-R571 - more later tonight.

**Comment by mikeysas** [comment]
@AF-1  - yes, happy to help with testing. 

I should have some time over the weekend to try a bunch of different options.

**Comment by michaelherger** [comment]
@AF-1 Material is not ready, yet. I've submitted a PR: https://github.com/CDrummond/lms-material/pull/1173

https://github.com/AF-1/lms-dynamicplaylists/pull/20 would add the renaming on playlist change. Requires the above PR.

**Comment by AF-1** [comment]
Thanks @michaelherger and @CDrummond . Seems to work fine.

@michaelherger You [mentioned](https://github.com/AF-1/lms-dynamicplaylists/issues/19#issuecomment-3737210096) that you discovered the missing param that was not passed to `Slim::Menu::BrowseLibrary::_albums` by inserting log statements. 
I've tried to add a dynamic discovery Home Extras slot for **_static playlists_** using `Slim::Menu::BrowseLibrary::_playlists`. 
But it shows all static playlists, some of them even twice. So I'd like to use log statements to see what's wrong. 
Which variable(s)/parameters in `Slim::Menu::BrowseLibrary::_albums` did you dump to see what was missing? 

BTW are the Material Home Extras Menu sorted (alphabetically or otherwise)? Sometimes the default  `Explore` menu is above, sometimes below or inbetween the DPL home extras memus.

P.S. If you pass a `subtitle` parameter value (HomeExtras.pm) to Material for a Home Extras menu, where and under which conditions would this subtitle be displayed? What's it for?

**Comment by michaelherger** [comment]
When you go to eg. https://github.com/LMS-Community/slimserver/blob/public/9.1/Slim/Menu/BrowseLibrary.pm#L2164, you could add something like 

```perl
warn Data::Dump::dump(@searchTags);
```

(or `$search`, `$args`, `$pt`, or all of them...)

The evaluation of the search terms is sometimes based on `$args`, some `$pt`. Try to figure out why it's not using what you're sending.

I'll leave the Material questions to @CDrummond to answer.

**Comment by AF-1** [comment]
@michaelherger I think `_playlists` is not intended for filtering individual playlists by ID. Looking at the playlists CLI query: it accepts folder_id for filtering folders, but not playlist_id for filtering individual playlists. The albums CLI query accepts album_id:XXX as a filter and then returns only that one album. Playlists does not do this with playlist_id. So I'm just going to remove the dyamic playlist discovery again. Well, it was worth a try.

**Comment by michaelherger** [comment]
But line 2161 does deal with a playlist id. What am I missing?

**Comment by AF-1** [comment]
@michaelherger Did you mean line 2161? The one about `library_id`? Anyway, I couldn't use _playlists from BrowsLibrary.pm because it seems to me that playlist_id is only used for _playlistTracks, not for _playlists. That's why the playlists CLI query completely ignored the playlist_id parameter and always returned all playlists, regardless of which playlist_id I passed. But maybe I missed something.
I ended up with [another solution](https://github.com/AF-1/lms-dynamicplaylists/blob/homeextras/DynamicPlaylists4/Plugin.pm#L7463): get all (static/normal) playlists, filter them by playlist_id and then create menu items in BrowseLibrary format.
From what I can see so far, it seems to work.

@mikeysas Take your time. And watch out for parameters in the UI template that do not exist in the template. After spending a long time working on SQLite statements, everything starts to look the same. 🤯

**Comment by mikeysas** [comment]
> [@mikeysas](https://github.com/mikeysas) Take your time. And watch out for parameters in the UI template that do not exist in the template. After spending a long time working on SQLite statements, everything starts to look the same. 🤯
>
I set an environment to test this and just got started.  Some general observations so far....

1) The options for any of the pre-defined Home Extras did not show up in Material's interface setting until I had created a DLPC with the Home Extra template and selected it in the DPL settings.  And even after that it took a shift-refresh of the browser, but then I had the one I defined and 3 other place holders.  I had refreshed and checked the Material Interface settings before setting anything up.  Not a big deal, but did make me wonder how that interaction is working and just wanted to share as the first set up here could confuse folks, but maybe a clear guide in your faq will cover it.

2) When I click and album from the Home Extra, I seem to be brought to "non-standard" Album Browse view.  As in, it is not the standard Material Album View.

Standard Album View:

<img width="633" height="702" alt="Image" src="https://github.com/user-attachments/assets/e1014d51-2e33-4834-b01e-2a270cb709f3" />


Album view when accessed from Dynamic Album Home Extra:

<img width="633" height="673" alt="Image" src="https://github.com/user-attachments/assets/3ad52555-d050-44a3-a1a1-1d846b5d80b1" />

I definitely prefer the standard view with the additional metadata and ratings.

3) In the latest git version of Material, @CDrummond has updated it based on feedback such that when you click more on Random Albums, the items that display in the full listing start with the ones that were from the Home Screen rather than a refreshed query.  See here for his comment https://forums.lyrion.org/forum/user-forums/3rd-party-software/106269-announce-material-skin?p=1807006#post1807006. If possible, I think the same behavior would be desirable here.

4) You were asking about the subtitle.  I believe it is the 2nd line of text you see on some of the items in the settings. You could add a note there to point them to DPL/DPLC maybe?

<img width="464" height="386" alt="Image" src="https://github.com/user-attachments/assets/ccb66bf9-e148-48a5-88dd-6464745f5b72" />

When I have some time later today I will start exercising various template selections and see if I find any issues with the SQL etc.

**Comment by mikeysas** [comment]
A couple more finds while testing.

I see this warning quite a bit in the server log
`[26-01-17 22:56:44.1529] Slim::Utils::Misc::msg (1320) Warning: [22:56:44.1525] Deep recursion on subroutine "Slim::Menu::BrowseLibrary::_albums" at /config/cache/InstalledPlugins/Plugins/DynamicPlaylists4/Plugin.pm line 7420.`

I also found that using specifying either option in the "only include albums if" parameter results in no home extra menu displaying.  If I leave that parameter blank, but still have a virtual library specified then the home extra does display.  I saw not error message in the server log specific to it not displaying.

<img width="933" height="154" alt="Image" src="https://github.com/user-attachments/assets/6060c826-bf81-4815-a53b-d1cd6af0cb8d" />

**Comment by mikeysas** [comment]
From my testing so far, it appears that when I restrict and album or artist list to a virtual library. that the VLC criteria are not included in what shows up in the Home Extra menu.  I have not tested it exhaustively, but I tried several different sets of criteria from VLC and none them seem to apply in the Home Extra and this was all without setting "Only include albums if."  The Home Extra displays, but only based on the criteria in the DLPC template parameters.

FYI on the browse menus.  They are different when going Artists home extras, but still not using the standard Material views.  When I go Artist > Albums, I see ratings, but not of the other metadata on the album header or tracks (track artists).

**Comment by michaelherger** [comment]
> [@michaelherger](https://github.com/michaelherger) Did you mean line 2161? The one about `library_id`? Anyway, I couldn't use _playlists from BrowsLibrary.pm because it seems to me that playlist_id is only used for _playlistTracks, not for _playlists. That's why the playlists CLI query completely ignored the playlist_id parameter and always returned all playlists, regardless of which playlist_id I passed.

I didn't look into this in detail. But there's also handling of a `search` argument.

**Comment by AF-1** [comment]
@mikeysas Thank you for testing this so far. I've pushed some changes to the homeextras branch that should fix the VL problem. To use a VL as a constraint you have to set both settings "Only include..." and select a library.

I don't know how caching works in your browser, in Material or for Home Extras in particular. When you restart LMS (after a plugin update), at least the predefined scrollable list placeholders "Dynamic Albums Discovery" should be listed in the Material interface settings under scrollable lists that can be enabled. I have added a subtitle and a note to the DPLC HE templates that should guide users. 1. Got to DPLC to create a scrollable list. 2 Then go to the DPL plugin settings to assign it to one of the srollable list slots.

As for the way the menus look when you drill down into artists, albums or playlists, I agree that the Material standard view looks much better. It is no suprise that my menus look different: basically I use BrowseLibrary (LMS core) for the menu items while @CDrummond uses his own browsing logic in Material and can therefore present items any way he likes. Mine look as if you were opening them using the Default / Logic Teal skin (no duration or meta information). The appended rating is provided by Ratings Light so it's there regardless. As a 3rd party plugin providing Home Extra items, I don't think I can make Material present items the way Craig presents them. I wonder if this is a dealbreaker, i.e. if I should stop this experiment. What you do think?

**Comment by CDrummond** [comment]
The best way would be to return the albums using "albums_loop" - this would then have the required meta-data.

An alternative is to supply the extra meta-data in the SlimBrowse "items_loop" - there is an un-merged pull request in LMS for this: https://github.com/LMS-Community/slimserver/pull/1405 (which Material has support for) ...but I like Darrell's suggestion in https://github.com/LMS-Community/slimserver/pull/1452

Material tries to avoid using BlowseLibrary/SlimBrowse because of the lack of meta-data - all responses are just a list of items, and a client has no idea what each item is. The API that Material uses, however, is also "LMS Core" - its all provided by LMS.

**Comment by mikeysas** [comment]
@AF-1  - VL fix for Albums looks great.  But I think I am still seeing the same issue with VL selection on the Artist Home Extra.  I am hoping Craig's suggestion above is workable.

@CDrummond - this may be a Material issue?
Another side observation I have noticed while testing is that if I update multiple DLPC templates at once, then a single click of the back button in Material does not take you back to the home page.  You seem to click back as many time as changes made. I noticed the same behavior with VLC which suggest it is certainly not related to these changes specifically and could be related to a recent change in Material.  I am posting the note here since it was while I was testing this, but I could replicate this in my production LMS (which is also 9.1 now, but not with these changes here).  I am pretty sure this was previously not a problem a while, but not sure if a change in these plugins or Material is the cause.  It is easy enough to recreate by just going into DLPC in Material and creating a new custom DLP and then click back and then you have to click back again to get to the home screen. If you create two of them in a row, you will have to click back more times.

**Comment by mikeysas** [comment]
Adding a comment to prevent this from closing for being stale.

@AF-1, just confirming you are still interested in working on this.  No rush of course as I understand you are not a big Material user and may have more important things to deal with in your life.

**Comment by AF-1** [comment]
@mikeysas I have spent quite some time trying to make Material display the items (albums in our example) **with** metadata, providing Material with all the necessary possible album metadata, even included some internal (Material) flags at some point, and tried many ways/formats (albums_loop incl.). Material never once displayed the metadata in the DPL albums HomeExtra.
The JSON response suggests that the metadata I provide is lost somewhere in the Material blackbox. If I had to guess, maybe in the Javascript part. I'm not a Material expert, nor do I intend to become one.
Without the metadata, it doesn't look nice. And it would ruin the impression of a consistent-looking UI.
The next updates of DPL / DPLC will probably just about SQLite bug fixes.

**Comment by mikeysas** [comment]
@AF-1 I really appreciate all the time you put into attempting to get this to work.  I get and respect your priorities.  Maybe @michaelherger or @CDrummond will have a simple suggestion to help, but I understand it may not their priority to spend time on this either.

Based on multiple requests on the forum, there are users in addition to myself interested in a solution for displaying a list of random albums filtered by criteria like you can in your DLPC album templates, but maybe there is a better way to approach that outside DPL/DPLC.

Thanks!

**Comment by michaelherger** [comment]
I'm sorry, currently got too many things going on... I've somewhat lost track of this one.

As I don't know exactly what is failing in what way, I'm probably saying something obvious: the returned data should be like a SlimBrowse menu item. Which comes with its own limitations. A raw loop, as you mentioned, likely wouldn't work.
